//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogId { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string Message { get; set; }
        public string ClassName { get; set; }
        public string ActivityId { get; set; }
        public int SourceId { get; set; }
        public string SourceType { get; set; }
        public string Category { get; set; }
    }
}
