//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int OrgaizationID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
    }
}
