//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int AuditId { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string SourceId { get; set; }
        public string AuditType { get; set; }
        public string AuditMessage { get; set; }
        public string ParticipantId { get; set; }
        public string ParticipantType { get; set; }
    }
}
