//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NGODBEntities : DbContext
    {
        public NGODBEntities()
            : base("name=NGODBEntities")
        {
            base.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Audit> Audits { get; set; }
        public virtual DbSet<ConfigSetting> ConfigSettings { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
    }
}
